<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
/** @var \Magefan\FacebookPixel\Block\Pixel $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var Magefan\Community\View\Helper\SecureHtmlRenderer $mfSecureRenderer */
?>
<?php
if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}

$script = '';
?>
<?php
    $script .= "
    !function(f,n){
        if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments);
            var ce = new CustomEvent('mf_fbq', {detail: arguments});
            document.dispatchEvent(ce);
        };
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];
        f.mfFbq = 1;
        
        let customerData = localStorage.getItem('mage-cache-storage') ? JSON.parse(localStorage.getItem('mage-cache-storage')).customer : false;
        let advancedMatching = (customerData && customerData.mf_fb_pixel_customer_data) ? customerData.mf_fb_pixel_customer_data : {};

        fbq('init', '{$escaper->escapeHtml($block->getFbPixelId())}', advancedMatching);
        fbq('track', 'PageView', {}, {'eventID': 'PageView' + '.' + Math.floor(Math.random() * 1000000) + '.' + Date.now()});
        var triedToLoadPixel = false;
    ";


    if ($block->isSpeedOptimizationEnabled() && $block->getRequest()->getModuleName() !== 'checkout') {
        $script .= "
            var actionDetected = false;
            document.addEventListener('scroll', initMfFbPixel);
            document.addEventListener('mousemove', initMfFbPixel);
            document.addEventListener('touchstart', initMfFbPixel);
            function initMfFbPixel()
            {
                if (actionDetected) return false;
                document.removeEventListener('scroll', initMfFbPixel);
                document.removeEventListener('mousemove', initMfFbPixel);
                document.removeEventListener('touchstart', initMfFbPixel);
                actionDetected = true;

                if (triedToLoadPixel) {
                    mfLoadFbPixel();
                }
            };
        ";
    } else {
        $script .= "
            var actionDetected = true;
        ";
    }

    $script .= "
        function mfLoadFbPixel() {
            triedToLoadPixel = true;
            if (!actionDetected) return false;
            !function(f,b,e,v,n,t,s){
                if (f.fbq && !f.mfFbq) return;
                t=b.createElement(e);t.async=!0;
                t.src=v;s=b.getElementsByTagName(e)[0];
                s.parentNode.insertBefore(t,s)
            }(window, document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');
        }
    ";


    if ($block->isProtectCustomerDataEnabled()) {
        $script .= "
        document.addEventListener('DOMContentLoaded', function () {
            function getCookieValue(cookieName) {
                let name = cookieName + '=';
                let cookieSplit = document.cookie.split(';');

                for (let i = 0; i < cookieSplit.length; i++) {
                    let a = cookieSplit[i];

                    while (a.charAt(0) === ' ') {
                        a = a.substring(1);
                    }

                    if (a.indexOf(name) === 0) {
                        return a.substring(name.length, a.length);
                    }
                }
                return '';
            }

            function customerDataAllowed() {
                let cookie = getCookieValue(
                    '{$escaper->escapeHtml(\Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE)}'
                );
                if (cookie) {
                    cookie = JSON.parse(decodeURIComponent(cookie));
                    if (cookie[{$escaper->escapeHtml($block->getWebsiteId())}]) {
                        return true;
                    }
                }

                return false
            }

            if (customerDataAllowed()) {
                mfLoadFbPixel();
            } else {
                let interval = setInterval(function () {
                    if (!customerDataAllowed()) return;
                    clearInterval(interval);
                    mfLoadFbPixel();
                }, 1000);
            }
        });
        ";


    } else {
        $script .= "
            mfLoadFbPixel();
        ";
    }

    $script .= "
        }(window);
    ";
?>
<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
