<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
/** @var \Magefan\FacebookPixel\Block\Adminhtml\System\Config\Form\EventList $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php
if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>
<?php
$events = [
    'View Product (ViewContent)',
    'View Checkout (InitiateCheckout)',
    'Checkout Success Page (Purchase)'
];
$eventsPlus = [
    'Add To Cart (AddToCart)',
    'Add To Wishlist (AddToWishlist)',
    'View Product List on category page, related/up-sell/cross-sell products (ViewCategory)',
    'Payments Step on Checkout Page (AddPaymentInfo)'
];
$eventsExtra = [
    'Search (Search)',
    'Complete Registration (CompleteRegistration)',
    'Contact (Contact)',
    'Customize Product (CustomizeProduct)'
];
?>
<br/>
<div>
    <ul>
        <li>
            <?= implode('</li><li>', $events) ?>
        </li>
    </ul>
    <p <?php if (!$block->isPlusEnabled()) { ?>style="color: #eb5202"<?php } ?>>
        <strong>
            <?= $escaper->escapeHtml(__(!$block->isPlusEnabled() ? 'Available in FB Pixel Plus Only' : 'FB Pixel Plus')) ?>
            <?php if (!$block->isPlusEnabled()) { ?>
                (<a style="color: #eb5202; text-decoration: underline;" href="https://magefan.com/magento-2-facebook-pixel/pricing" target="_blank">Read more</a>):
            <?php } ?>
        </strong>
    </p>
    <div <?php if (!$block->isPlusEnabled()) { ?>style="opacity: 0.7; color: #eb5202"<?php } ?>>
        <ul>
            <li>
                <?= implode('</li><li>', $eventsPlus) ?>
            </li>
        </ul>
    </div>
    <p <?php if (!$block->isExtraEnabled()) { ?>style="color: #eb5202"<?php } ?>>
        <strong>
            <?= $escaper->escapeHtml(
                __(!$block->isExtraEnabled() ? 'Available in FB Pixel Extra Only' : 'FB Pixel Extra')
            ) ?>
            <?php if (!$block->isExtraEnabled()) { ?>
                (<a style="color: #eb5202; text-decoration: underline;" href="https://magefan.com/magento-2-facebook-pixel/pricing" target="_blank">Read more</a>):
            <?php } ?>
        </strong>
    </p>
    <div <?php if (!$block->isExtraEnabled()) { ?>style="opacity: 0.7; color: #eb5202"<?php } ?>>
        <ul>
            <li>
                <?= implode('</li><li>', $eventsExtra) ?>
            </li>
        </ul>
    </div>
</div>
